CREATE TABLE IF NOT EXISTS departments(id BIGSERIAL PRIMARY KEY,external_id INTEGER UNIQUE,name TEXT NOT NULL UNIQUE,active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS schedule_templates(id BIGSERIAL PRIMARY KEY,code TEXT NOT NULL UNIQUE,name TEXT NOT NULL,start_time TIME NOT NULL,end_time TIME NOT NULL,crosses_midnight BOOLEAN NOT NULL DEFAULT FALSE,paid_hours NUMERIC(5,2) NOT NULL,lunch_minutes INTEGER NOT NULL DEFAULT 60,no_lunch BOOLEAN NOT NULL DEFAULT FALSE);
ALTER TABLE schedule_templates ADD COLUMN IF NOT EXISTS schedule_kind TEXT NOT NULL DEFAULT 'weekly';
ALTER TABLE schedule_templates ADD COLUMN IF NOT EXISTS cycle_pattern JSONB;
ALTER TABLE schedule_templates ADD COLUMN IF NOT EXISTS requires_anchor BOOLEAN NOT NULL DEFAULT FALSE;
CREATE TABLE IF NOT EXISTS employees(id INTEGER PRIMARY KEY,full_name TEXT NOT NULL,first_name TEXT,patronymic TEXT,department_id BIGINT REFERENCES departments(id),card_number TEXT,gender TEXT,email TEXT,position_name TEXT,hired_at DATE,active BOOLEAN NOT NULL DEFAULT TRUE,clean_time_calculation BOOLEAN NOT NULL DEFAULT FALSE,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
ALTER TABLE employees ADD COLUMN IF NOT EXISTS needs_review BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS review_note TEXT;
CREATE TABLE IF NOT EXISTS employee_schedules(id BIGSERIAL PRIMARY KEY,employee_id INTEGER NOT NULL REFERENCES employees(id),schedule_id BIGINT NOT NULL REFERENCES schedule_templates(id),effective_from DATE NOT NULL DEFAULT '2000-01-01',effective_to DATE,source TEXT NOT NULL DEFAULT 'WorkSchedule',UNIQUE(employee_id,effective_from));
CREATE TABLE IF NOT EXISTS schedule_overrides(id BIGSERIAL PRIMARY KEY,employee_id INTEGER NOT NULL REFERENCES employees(id),work_date DATE NOT NULL,start_time TIME NOT NULL,end_time TIME NOT NULL,reason TEXT NOT NULL,comment TEXT,changed_by TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),UNIQUE(employee_id,work_date));
ALTER TABLE schedule_overrides DROP CONSTRAINT IF EXISTS schedule_overrides_employee_id_work_date_key;
ALTER TABLE schedule_overrides ADD COLUMN IF NOT EXISTS leave_minutes INTEGER NOT NULL DEFAULT 0;
ALTER TABLE schedule_overrides ADD COLUMN IF NOT EXISTS combo_hours NUMERIC(6,2) NOT NULL DEFAULT 0;
ALTER TABLE schedule_overrides ADD COLUMN IF NOT EXISTS overtime_hours NUMERIC(6,2) NOT NULL DEFAULT 0;
ALTER TABLE schedule_overrides ADD COLUMN IF NOT EXISTS combo_employee_id INTEGER REFERENCES employees(id);
ALTER TABLE schedule_overrides ADD COLUMN IF NOT EXISTS combo_employee_name TEXT;
CREATE TABLE IF NOT EXISTS skud_days(id BIGSERIAL PRIMARY KEY,employee_id INTEGER NOT NULL REFERENCES employees(id),work_date DATE NOT NULL,entry_time TIME,end_time TIME,fact_hours NUMERIC(6,2) NOT NULL DEFAULT 0,total_hours NUMERIC(6,2) NOT NULL DEFAULT 0,combo_hours NUMERIC(6,2) NOT NULL DEFAULT 0,status TEXT NOT NULL,record_count INTEGER NOT NULL DEFAULT 0,issues JSONB NOT NULL DEFAULT '[]'::jsonb,source TEXT NOT NULL DEFAULT 'skud_import',imported_at TIMESTAMPTZ NOT NULL DEFAULT now(),UNIQUE(employee_id,work_date));
CREATE INDEX IF NOT EXISTS idx_skud_days_lookup ON skud_days(employee_id,work_date);
CREATE TABLE IF NOT EXISTS department_schedules(id BIGSERIAL PRIMARY KEY,department_id BIGINT NOT NULL REFERENCES departments(id),schedule_id BIGINT NOT NULL REFERENCES schedule_templates(id),effective_from DATE NOT NULL,effective_to DATE,source TEXT NOT NULL DEFAULT 'manual',UNIQUE(department_id,effective_from));
CREATE TABLE IF NOT EXISTS app_accounts(login TEXT PRIMARY KEY,full_name TEXT NOT NULL,password TEXT NOT NULL,role TEXT NOT NULL CHECK(role IN('admin','observer','boss')),employee_ids JSONB NOT NULL DEFAULT '[]'::jsonb,department_ids JSONB NOT NULL DEFAULT '[]'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_employees_department ON employees(department_id);
CREATE INDEX IF NOT EXISTS idx_employee_schedules_lookup ON employee_schedules(employee_id,effective_from,effective_to);
CREATE INDEX IF NOT EXISTS idx_department_schedules_lookup ON department_schedules(department_id,effective_from,effective_to);
